language: node_js
node_js:
  - "6.9.1"

branches:
  only:
    - master

before_script:
  - npm install

script:
  - react-scripts build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build/
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
